[platformio]
default_envs = node_polling

[env]
build_flags = -std=gnu++17 -Wall -Wextra

[teensy_base]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200
upload_protocol = teensy-cli
lib_deps =
    adafruit/Adafruit BNO055@^1.6.3
    mikem/RadioHead@^1.120

[env:node_polling]
extends = teensy_base
build_src_filter = +<*> -<gateway_main.cpp>
build_flags = ${env.build_flags} -D FLOODNET_SAMPLER_POLLING

[env:gateway]
extends = teensy_base
build_src_filter = +<*> -<main.cpp> -<sampler_polling.cpp>

[env:native]
platform = native
lib_compat_mode = off
test_build_src = yes
build_flags = ${env.build_flags} -I src
lib_deps =
    floodnet_core
    floodnet_hal
