#include <unity.h>
#include <floodnet/packet.hpp>

using namespace floodnet;

void setUp(void) {}
void tearDown(void) {}

static Packet make_packet(void) {
    Packet p;
    p.node_id = 0x1234;
    p.seq = 0xDEADBEEF;
    p.ttl = 3;
    p.flags = 0x5A;  // distinctive non-zero: nothing round-trips this by accident
    p.record.gps.time_ms = 1000;
    p.record.gps.lat_1e7 = 481173000;
    p.record.gps.lon_1e7 = -115166667;
    p.record.gps.alt_mm = 545400;
    p.record.gps.satellites = 8;
    p.record.gps.valid = true;
    p.record.imu.time_ms = 995;
    p.record.imu.yaw_cd = -4500;
    p.record.imu.pitch_cd = 250;
    p.record.imu.roll_cd = -300;  // distinctive non-zero; was 0, which let a bug at
                                   // offsets 36-37 round-trip cleanly and go unnoticed
    p.record.imu.valid = true;
    p.record.diag.drops = 7;
    p.record.diag.crc_errors = 2;
    return p;
}

void test_crc16_matches_known_vector(void) {
    // CRC16-CCITT-FALSE of "123456789" is 0x29B1.
    const uint8_t input[] = {'1', '2', '3', '4', '5', '6', '7', '8', '9'};
    TEST_ASSERT_EQUAL_HEX16(0x29B1, crc16_ccitt(input, sizeof(input)));
}

void test_encode_returns_packet_size(void) {
    uint8_t buf[PACKET_SIZE];
    TEST_ASSERT_EQUAL_UINT(PACKET_SIZE, encode_packet(make_packet(), buf, sizeof(buf)));
}

void test_encode_rejects_short_buffer(void) {
    uint8_t buf[PACKET_SIZE - 1];
    TEST_ASSERT_EQUAL_UINT(0, encode_packet(make_packet(), buf, sizeof(buf)));
}

void test_round_trip_preserves_every_field(void) {
    uint8_t buf[PACKET_SIZE];
    Packet original = make_packet();
    TEST_ASSERT_EQUAL_UINT(PACKET_SIZE, encode_packet(original, buf, sizeof(buf)));

    Packet decoded;
    TEST_ASSERT_TRUE(decode_packet(buf, sizeof(buf), &decoded));

    TEST_ASSERT_EQUAL_UINT16(original.node_id, decoded.node_id);
    TEST_ASSERT_EQUAL_UINT32(original.seq, decoded.seq);
    TEST_ASSERT_EQUAL_UINT8(original.ttl, decoded.ttl);
    TEST_ASSERT_EQUAL_UINT8(original.flags, decoded.flags);
    TEST_ASSERT_EQUAL_UINT32(original.record.gps.time_ms, decoded.record.gps.time_ms);
    TEST_ASSERT_EQUAL_INT32(original.record.gps.lat_1e7, decoded.record.gps.lat_1e7);
    TEST_ASSERT_EQUAL_INT32(original.record.gps.lon_1e7, decoded.record.gps.lon_1e7);
    TEST_ASSERT_EQUAL_INT32(original.record.gps.alt_mm, decoded.record.gps.alt_mm);
    TEST_ASSERT_EQUAL_UINT8(original.record.gps.satellites, decoded.record.gps.satellites);
    TEST_ASSERT_TRUE(decoded.record.gps.valid);
    TEST_ASSERT_EQUAL_UINT32(original.record.imu.time_ms, decoded.record.imu.time_ms);
    TEST_ASSERT_EQUAL_INT16(original.record.imu.yaw_cd, decoded.record.imu.yaw_cd);
    TEST_ASSERT_EQUAL_INT16(original.record.imu.pitch_cd, decoded.record.imu.pitch_cd);
    TEST_ASSERT_EQUAL_INT16(original.record.imu.roll_cd, decoded.record.imu.roll_cd);
    TEST_ASSERT_TRUE(decoded.record.imu.valid);
    TEST_ASSERT_EQUAL_UINT16(original.record.diag.drops, decoded.record.diag.drops);
    TEST_ASSERT_EQUAL_UINT16(original.record.diag.crc_errors, decoded.record.diag.crc_errors);
}

// Pins the exact 45-byte wire layout. Consistently shuffling fields in BOTH
// encode_packet() and decode_packet() would leave every other test in this
// file passing, because nothing else checks an actual byte position, and a
// later host parser must match this layout exactly. If this test fails, the
// wire layout changed and every consumer of it must be updated. The expected
// array below was generated by encoding make_packet() once and printing the
// bytes; it is not a value someone typed from memory.
void test_golden_vector_pins_byte_layout(void) {
    uint8_t buf[PACKET_SIZE];
    TEST_ASSERT_EQUAL_UINT(PACKET_SIZE, encode_packet(make_packet(), buf, sizeof(buf)));

    static const uint8_t expected[PACKET_SIZE] = {
        0xFD, 0x01, 0x34, 0x12, 0xEF, 0xBE, 0xAD, 0xDE, 0x03, 0x5A,
        0xE8, 0x03, 0x00, 0x00, 0x08, 0x1E, 0xAE, 0x1C, 0x35, 0xB2,
        0x22, 0xF9, 0x78, 0x52, 0x08, 0x00, 0x08, 0x01, 0xE3, 0x03,
        0x00, 0x00, 0x6C, 0xEE, 0xFA, 0x00, 0xD4, 0xFE, 0x01, 0x07,
        0x00, 0x02, 0x00, 0x73, 0xD8,
    };
    TEST_ASSERT_EQUAL_UINT8_ARRAY(expected, buf, PACKET_SIZE);
}

void test_decode_rejects_corrupted_payload(void) {
    uint8_t buf[PACKET_SIZE];
    encode_packet(make_packet(), buf, sizeof(buf));
    buf[20] ^= 0xFF;  // flip bits inside the longitude field

    Packet decoded;
    TEST_ASSERT_FALSE(decode_packet(buf, sizeof(buf), &decoded));
}

void test_decode_rejects_bad_magic(void) {
    uint8_t buf[PACKET_SIZE];
    encode_packet(make_packet(), buf, sizeof(buf));
    buf[0] = 0x00;

    Packet decoded;
    TEST_ASSERT_FALSE(decode_packet(buf, sizeof(buf), &decoded));
}

void test_decode_rejects_wrong_length(void) {
    uint8_t buf[PACKET_SIZE];
    encode_packet(make_packet(), buf, sizeof(buf));

    Packet decoded;
    TEST_ASSERT_FALSE(decode_packet(buf, PACKET_SIZE - 1, &decoded));
}

int main(int, char **) {
    UNITY_BEGIN();
    RUN_TEST(test_crc16_matches_known_vector);
    RUN_TEST(test_encode_returns_packet_size);
    RUN_TEST(test_encode_rejects_short_buffer);
    RUN_TEST(test_round_trip_preserves_every_field);
    RUN_TEST(test_golden_vector_pins_byte_layout);
    RUN_TEST(test_decode_rejects_corrupted_payload);
    RUN_TEST(test_decode_rejects_bad_magic);
    RUN_TEST(test_decode_rejects_wrong_length);
    return UNITY_END();
}
